title: ask the data

repository: bird70/ask-the-data
url: https://bird70.github.io/ask-the-data

# theme: minima
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
