title: ask the data

repository: bird70/ask-the-data
url: https://bird70.github.io
baseurl: /ask-the-data
permalink: pretty

description: A blog about data, GIS, and cloud technology.

# Minimal Mistakes Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
locale: "en-US"
title_separator: "-"
subtitle: "A blog about data, GIS, and cloud technology"
breadcrumbs: true
words_per_minute: 200

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compress-images
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Site Author
author:
  name: "Tilmann Steinmetz"
  bio: "Data professional working with GIS and cloud technology"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bird70"

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# # Social Sharing
# twitter:
#   username: # your Twitter username (optional)

# Analytics (optional)
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag", "custom"