---
layout: post
author: Tilmann Steinmetz
image: /assets/images/PA1Screenshot.png
---
A while ago, I was looking for a way to deal with web orders that our team was receiving as emails. The emails were generated by some form of
ancient website form, and one of the team would usually be so confused by what little legible content there was in the orders that they
would first make a call to the ordering customer to check what the order was actually for (yes, we knew it wasn't great, and we really wanted to 
move away from it but it wasn't something we had any control over).

![PowerAutomate Workflow]({{site.url}}/assets/images/PA1Screenshot.png "workflow")

As an initial improvement, I designed a workflow in Microsoft PowerAutomate which would parse the contents of the email and create a Microsoft  Planner Task that could be
assigned to a team member.

![PowerAutomate Workflow]({{site.url}}/assets/images/PA2Screenshot.png "workflow")

The workflow was able to do that easily for the volume of orders arriving in our mailbox and as an outcome, we had a nice visual way to keep track of orders.
The Planner Board was set up such, that we had different swimlanes for the different states of the order - so the team could move them from "Open"
to "Complete" via manual state transitions. It gave us a way to have an easy way to track all orders - and for the first time handover
between different team members didn't require long explanations!

Here's roughly what the PowerAutomate Flow did:

1) Monitor an email inbox. 
2) When new email arrived, parse the email, to extract the Subject, Sender Address, Content etc. (the format that came from the web form was really rather
painful to parse, but eventually, this worked pretty reliably)
3) The previously extracted parts were then used to assemble a new 'card' on the Planner Board which was added in the "Open Orders" Swimlane (and optionally assigned to a team member)
4) The workflow also assembled an email reply that capture the received order message contents, contained payment information and some other detail, and was sent so the customer knew we have received the order

We would have loved to have automatic payments etc., but all of that would have to wait a bit longer for the web team to make a new site, unfortunately.
With the simple workflow above though, we were at least able to give customers immediate re-assurance that their order was received and 
taken good care of, while internally we were delighted that at last we had a good overview of which orders were in what state and who was dealing with them.


![Workflow4]({{site.url}}/assets/images/PA4Screenshot.png "areas")
![Workflow7]({{site.url}}/assets/images/PA7Screenshot.png "areas")

